namespace TFS_Parser.Entities
{
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.EntityFrameworkCore;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 


    /// <remarks/>
 
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class ROOT
    {
        /// <remarks/>
        [XmlArray(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("TFS", typeof(ROOTMAINLISTTFS),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTMAINLISTTFS> MAINLIST { get; set; }
        
        /// <remarks/>
        [XmlArray(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("ANCS", typeof(ROOTANCESTORLISTANCS),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTANCESTORLISTANCS> ANCESTORLIST{ get; set; }

        /// <remarks/>
        [XmlArray(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("ALT", typeof(ROOTALTERNATELISTALT),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTALTERNATELISTALT> ALTERNATELIST{ get; set; }
        
        /// <remarks/>
        [XmlArray(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("OGR", typeof(ROOTOGRSOVMLISTOGR),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTOGRSOVMLISTOGR> OGRSOVMLIST{ get; set; }

        /// <remarks/>
        [XmlElement("TYPEPARAM", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTTYPEPARAM> TYPEPARAM { get; set; }

        /// <remarks/>
        [XmlElement("TYPEDECISION", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTTYPEDECISION> TYPEDECISION { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public class ROOTANCESTORLISTANCS
    {
        /// <remarks/>
        [XmlIgnore]
        public int TFSID_DB { get; set; }
        
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
            
        /// <remarks/>
        [XmlAttribute]
        public string IdBlock { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public string IdShapeAncestor { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public class ROOTOGRSOVMLISTOGR
    {
        [XmlIgnore]
        public int TFSID_DB { get; set; }
        
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
            
        /// <remarks/>
        [XmlAttribute]
        public string Row { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public string Col { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class ROOTMAINLISTTFS
    {
        /// <remarks/>
        [XmlIgnore]
        public int TFSID_DB { get; set; }
        
        /// <remarks/>
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
        
        /// <remarks/>
        [XmlElement("TFE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTMAINLISTTFSTFE> TFE { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string ID  {get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string TypeID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string StartPointX { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string StartPointY { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string OffsetX { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string OffsetY { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string NextID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string PriorID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class ROOTMAINLISTTFSTFE
    {

        /// <remarks/>
        [XmlArray(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("ParamAlt", typeof(ROOTMAINLISTTFSTFEPARAMSParamAlt),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTMAINLISTTFSTFEPARAMSParamAlt> PARAMS { get; set; }
        
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string ID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string TypeID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    //[Keyless]
    //[NotMapped]
    public partial class ROOTMAINLISTTFSTFEPARAMSParamAlt
    {
        #region fields
        
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
        
        private string nUMBERField;

        private string pRED_ISTORField;

        private string sOSTAVField;

        private string nAMEField;

        private string fUNCTIONField;

        private string eLEMENTField;

        private string pREDICATField;

        private string bField;

        private string tField;

        private string vField;

        private string a1_B_FField;

        private string b_F1NField;

        private string b_F1BField;

        private string a2_B_FField;

        private string b_F2NField;

        private string b_F2BField;

        private string a3_B_FField;

        private string b_F3NField;

        private string b_F3BField;

        private string a1_T_FField;

        private string t_F1NField;

        private string t_F1BField;

        private string a2_T_FField;

        private string t_F2NField;

        private string t_F2BField;

        private string a3_T_FField;

        private string t_F3NField;

        private string t_F3BField;

        private string a1_V_FField;

        private string v_F1NField;

        private string v_F1BField;

        private string a2_V_FField;

        private string v_F2NField;

        private string v_F2BField;

        private string a3_V_FField;

        private string v_F3NField;

        private string v_F3BField;

        private string k_11Field;

        private string k_00Field;

        private string t_FField;

        private string v_FField;

        private string a1_K11_FField;

        private string k11_F1NField;

        private string k11_F1BField;

        private string a2_K11_FField;

        private string k11_F2NField;

        private string k11_F2BField;

        private string a3_K11_FField;

        private string k11_F3NField;

        private string k11_F3BField;

        private string a1_K00_FField;

        private string k00_F1NField;

        private string k00_F1BField;

        private string a2_K00_FField;

        private string k00_F2NField;

        private string k00_F2BField;

        private string a3_K00_FField;

        private string k00_F3NField;

        private string k00_F3BField;

        private string a1_TF_FField;

        private string tF_F1NField;

        private string tF_F1BField;

        private string a2_TF_FField;

        private string tF_F2NField;

        private string tF_F2BField;

        private string a3_TF_FField;

        private string tF_F3NField;

        private string tF_F3BField;

        private string a1_VF_FField;

        private string vF_F1NField;

        private string vF_F1BField;

        private string a2_VF_FField;

        private string vF_F2NField;

        private string vF_F2BField;

        private string a3_VF_FField;

        private string vF_F3NField;

        private string vF_F3BField;

        private string p_11Field;

        private string p_00Field;

        private string t_DField;

        private string v_DField;

        private string a1_P11_FField;

        private string p11_F1NField;

        private string p11_F1BField;

        private string a2_P11_FField;

        private string p11_F2NField;

        private string p11_F2BField;

        private string a3_P11_FField;

        private string p11_F3NField;

        private string p11_F3BField;

        private string a1_P00_FField;

        private string p00_F1NField;

        private string p00_F1BField;

        private string a2_P00_FField;

        private string p00_F2NField;

        private string p00_F2BField;

        private string a3_P00_FField;

        private string p00_F3NField;

        private string p00_F3BField;

        private string a1_TD_FField;

        private string tD_F1NField;

        private string tD_F1BField;

        private string a2_TD_FField;

        private string tD_F2NField;

        private string tD_F2BField;

        private string a3_TD_FField;

        private string tD_F3NField;

        private string tD_F3BField;

        private string a1_VD_FField;

        private string vD_F1NField;

        private string vD_F1BField;

        private string a2_VD_FField;

        private string vD_F2NField;

        private string vD_F2BField;

        private string a3_VD_FField;

        private string vD_F3NField;

        private string vD_F3BField;

        private string tYPEField;

        private string eLEM_DIAGNField;

        private string p_DIAGN_ELField;

        private string a1_P_EL_FField;

        private string p_EL_F1NField;

        private string p_EL_F1BField;

        private string a2_P_EL_FField;

        private string p_EL_F2NField;

        private string p_EL_F2BField;

        private string a3_P_EL_FField;

        private string p_EL_F3NField;

        private string p_EL_F3BField;

        private string sOVMField;

        private string sOVM0Field;

        private string sOVM1Field;
        
        #endregion

        #region properties

        /// <remarks/>
        [XmlAttribute]
        public string NUMBER
        {
            get { return nUMBERField; }
            set { nUMBERField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string PRED_ISTOR
        {
            get { return pRED_ISTORField; }
            set { pRED_ISTORField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string SOSTAV
        {
            get { return sOSTAVField; }
            set { sOSTAVField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string NAME
        {
            get { return nAMEField; }
            set { nAMEField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string FUNCTION
        {
            get { return fUNCTIONField; }
            set { fUNCTIONField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string ELEMENT
        {
            get { return eLEMENTField; }
            set { eLEMENTField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string PREDICAT
        {
            get { return pREDICATField; }
            set { pREDICATField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string B
        {
            get { return bField; }
            set { bField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T
        {
            get { return tField; }
            set { tField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V
        {
            get { return vField; }
            set { vField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_B_F
        {
            get { return a1_B_FField; }
            set { a1_B_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string B_F1N
        {
            get { return b_F1NField; }
            set { b_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string B_F1B
        {
            get { return b_F1BField; }
            set { b_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_B_F
        {
            get { return a2_B_FField; }
            set { a2_B_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string B_F2N
        {
            get { return b_F2NField; }
            set { b_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string B_F2B
        {
            get { return b_F2BField; }
            set { b_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_B_F
        {
            get { return a3_B_FField; }
            set { a3_B_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string B_F3N
        {
            get { return b_F3NField; }
            set { b_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string B_F3B
        {
            get { return b_F3BField; }
            set { b_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_T_F
        {
            get { return a1_T_FField; }
            set { a1_T_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_F1N
        {
            get { return t_F1NField; }
            set { t_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_F1B
        {
            get { return t_F1BField; }
            set { t_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_T_F
        {
            get { return a2_T_FField; }
            set { a2_T_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_F2N
        {
            get { return t_F2NField; }
            set { t_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_F2B
        {
            get { return t_F2BField; }
            set { t_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_T_F
        {
            get { return a3_T_FField; }
            set { a3_T_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_F3N
        {
            get { return t_F3NField; }
            set { t_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_F3B
        {
            get { return t_F3BField; }
            set { t_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_V_F
        {
            get { return a1_V_FField; }
            set { a1_V_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_F1N
        {
            get { return v_F1NField; }
            set { v_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_F1B
        {
            get { return v_F1BField; }
            set { v_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_V_F
        {
            get { return a2_V_FField; }
            set { a2_V_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_F2N
        {
            get { return v_F2NField; }
            set { v_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_F2B
        {
            get { return v_F2BField; }
            set { v_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_V_F
        {
            get { return a3_V_FField; }
            set { a3_V_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_F3N
        {
            get { return v_F3NField; }
            set { v_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_F3B
        {
            get { return v_F3BField; }
            set { v_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K_11
        {
            get { return k_11Field; }
            set { k_11Field = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K_00
        {
            get { return k_00Field; }
            set { k_00Field = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_F
        {
            get { return t_FField; }
            set { t_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_F
        {
            get { return v_FField; }
            set { v_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_K11_F
        {
            get { return a1_K11_FField; }
            set { a1_K11_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K11_F1N
        {
            get { return k11_F1NField; }
            set { k11_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K11_F1B
        {
            get { return k11_F1BField; }
            set { k11_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_K11_F
        {
            get { return a2_K11_FField; }
            set { a2_K11_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K11_F2N
        {
            get { return k11_F2NField; }
            set { k11_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K11_F2B
        {
            get { return k11_F2BField; }
            set { k11_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_K11_F
        {
            get { return a3_K11_FField; }
            set { a3_K11_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K11_F3N
        {
            get { return k11_F3NField; }
            set { k11_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K11_F3B
        {
            get { return k11_F3BField; }
            set { k11_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_K00_F
        {
            get { return a1_K00_FField; }
            set { a1_K00_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K00_F1N
        {
            get { return k00_F1NField; }
            set { k00_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K00_F1B
        {
            get { return k00_F1BField; }
            set { k00_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_K00_F
        {
            get { return a2_K00_FField; }
            set { a2_K00_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K00_F2N
        {
            get { return k00_F2NField; }
            set { k00_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K00_F2B
        {
            get { return k00_F2BField; }
            set { k00_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_K00_F
        {
            get { return a3_K00_FField; }
            set { a3_K00_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K00_F3N
        {
            get { return k00_F3NField; }
            set { k00_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string K00_F3B
        {
            get { return k00_F3BField; }
            set { k00_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_TF_F
        {
            get { return a1_TF_FField; }
            set { a1_TF_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TF_F1N
        {
            get { return tF_F1NField; }
            set { tF_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TF_F1B
        {
            get { return tF_F1BField; }
            set { tF_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_TF_F
        {
            get { return a2_TF_FField; }
            set { a2_TF_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TF_F2N
        {
            get { return tF_F2NField; }
            set { tF_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TF_F2B
        {
            get { return tF_F2BField; }
            set { tF_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_TF_F
        {
            get { return a3_TF_FField; }
            set { a3_TF_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TF_F3N
        {
            get { return tF_F3NField; }
            set { tF_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TF_F3B
        {
            get { return tF_F3BField; }
            set { tF_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_VF_F
        {
            get { return a1_VF_FField; }
            set { a1_VF_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VF_F1N
        {
            get { return vF_F1NField; }
            set { vF_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VF_F1B
        {
            get { return vF_F1BField; }
            set { vF_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_VF_F
        {
            get { return a2_VF_FField; }
            set { a2_VF_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VF_F2N
        {
            get { return vF_F2NField; }
            set { vF_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VF_F2B
        {
            get { return vF_F2BField; }
            set { vF_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_VF_F
        {
            get { return a3_VF_FField; }
            set { a3_VF_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VF_F3N
        {
            get { return vF_F3NField; }
            set { vF_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VF_F3B
        {
            get { return vF_F3BField; }
            set { vF_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_11
        {
            get { return p_11Field; }
            set { p_11Field = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_00
        {
            get { return p_00Field; }
            set { p_00Field = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string T_D
        {
            get { return t_DField; }
            set { t_DField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string V_D
        {
            get { return v_DField; }
            set { v_DField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_P11_F
        {
            get { return a1_P11_FField; }
            set { a1_P11_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P11_F1N
        {
            get { return p11_F1NField; }
            set { p11_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P11_F1B
        {
            get { return p11_F1BField; }
            set { p11_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_P11_F
        {
            get { return a2_P11_FField; }
            set { a2_P11_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P11_F2N
        {
            get { return p11_F2NField; }
            set { p11_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P11_F2B
        {
            get { return p11_F2BField; }
            set { p11_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_P11_F
        {
            get { return a3_P11_FField; }
            set { a3_P11_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P11_F3N
        {
            get { return p11_F3NField; }
            set { p11_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P11_F3B
        {
            get { return p11_F3BField; }
            set { p11_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_P00_F
        {
            get { return a1_P00_FField; }
            set { a1_P00_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P00_F1N
        {
            get { return p00_F1NField; }
            set { p00_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P00_F1B
        {
            get { return p00_F1BField; }
            set { p00_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_P00_F
        {
            get { return a2_P00_FField; }
            set { a2_P00_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P00_F2N
        {
            get { return p00_F2NField; }
            set { p00_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P00_F2B
        {
            get { return p00_F2BField; }
            set { p00_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_P00_F
        {
            get { return a3_P00_FField; }
            set { a3_P00_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P00_F3N
        {
            get { return p00_F3NField; }
            set { p00_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P00_F3B
        {
            get { return p00_F3BField; }
            set { p00_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_TD_F
        {
            get { return a1_TD_FField; }
            set { a1_TD_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TD_F1N
        {
            get { return tD_F1NField; }
            set { tD_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TD_F1B
        {
            get { return tD_F1BField; }
            set { tD_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_TD_F
        {
            get { return a2_TD_FField; }
            set { a2_TD_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TD_F2N
        {
            get { return tD_F2NField; }
            set { tD_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TD_F2B
        {
            get { return tD_F2BField; }
            set { tD_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_TD_F
        {
            get { return a3_TD_FField; }
            set { a3_TD_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TD_F3N
        {
            get { return tD_F3NField; }
            set { tD_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TD_F3B
        {
            get { return tD_F3BField; }
            set { tD_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_VD_F
        {
            get { return a1_VD_FField; }
            set { a1_VD_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VD_F1N
        {
            get { return vD_F1NField; }
            set { vD_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VD_F1B
        {
            get { return vD_F1BField; }
            set { vD_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_VD_F
        {
            get { return a2_VD_FField; }
            set { a2_VD_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VD_F2N
        {
            get { return vD_F2NField; }
            set { vD_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VD_F2B
        {
            get { return vD_F2BField; }
            set { vD_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_VD_F
        {
            get { return a3_VD_FField; }
            set { a3_VD_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VD_F3N
        {
            get { return vD_F3NField; }
            set { vD_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string VD_F3B
        {
            get { return vD_F3BField; }
            set { vD_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TYPE
        {
            get { return tYPEField; }
            set { tYPEField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string ELEM_DIAGN
        {
            get { return eLEM_DIAGNField; }
            set { eLEM_DIAGNField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_DIAGN_EL
        {
            get { return p_DIAGN_ELField; }
            set { p_DIAGN_ELField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A1_P_EL_F
        {
            get { return a1_P_EL_FField; }
            set { a1_P_EL_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_EL_F1N
        {
            get { return p_EL_F1NField; }
            set { p_EL_F1NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_EL_F1B
        {
            get { return p_EL_F1BField; }
            set { p_EL_F1BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A2_P_EL_F
        {
            get { return a2_P_EL_FField; }
            set { a2_P_EL_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_EL_F2N
        {
            get { return p_EL_F2NField; }
            set { p_EL_F2NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_EL_F2B
        {
            get { return p_EL_F2BField; }
            set { p_EL_F2BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string A3_P_EL_F
        {
            get { return a3_P_EL_FField; }
            set { a3_P_EL_FField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_EL_F3N
        {
            get { return p_EL_F3NField; }
            set { p_EL_F3NField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string P_EL_F3B
        {
            get { return p_EL_F3BField; }
            set { p_EL_F3BField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string SOVM
        {
            get { return sOVMField; }
            set { sOVMField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string SOVM0
        {
            get { return sOVM0Field; }
            set { sOVM0Field = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string SOVM1
        {
            get { return sOVM1Field; }
            set { sOVM1Field = value; }
        }
        
        #endregion
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class ROOTALTERNATELISTALT
    {
        /// <remarks/>
        [XmlElement("ITEM", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTALTERNATELISTALTITEM> ITEM { get; set; }

        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
        
        [XmlAttribute]
        public string ID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Num { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string NodeStartID { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string NodeEndID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class ROOTALTERNATELISTALTITEM
    {
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
        
        /// <remarks/>
        [XmlAttribute]
        public string ID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class ROOTTYPEPARAM
    {
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
        
        /// <remarks/>
        [XmlAttribute]
        public string Value { get; set; }
        
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class ROOTTYPEDECISION
    {
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
        
        /// <remarks/>
        [XmlElement("Params", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTTYPEDECISIONParams> Params { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Type { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string Sovm { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class ROOTTYPEDECISIONParams
    {
        [XmlIgnore]
        [Key]
        public int ID_DB  {get; set; }
        
        /// <remarks/>
        [XmlAttribute]
        public string V { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string T { get; set; }
        
        [XmlAttribute]
        public string B { get; set; }
        
        /// <remarks/>
        [XmlAttribute]
        public string VD{ get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string TD{ get; set; }
        
        [XmlAttribute]
        public string BD{ get; set; }
    }

}