using Microsoft.EntityFrameworkCore.Migrations;

namespace TFS_Parser.Migrations
{
    public partial class update : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ROOTMAINLISTTFSTFEPARAMSParamAlt",
                columns: table => new
                {
                    ID = table.Column<string>(type: "text", nullable: false),
                    NUMBER = table.Column<string>(type: "text", nullable: true),
                    PRED_ISTOR = table.Column<string>(type: "text", nullable: true),
                    SOSTAV = table.Column<string>(type: "text", nullable: true),
                    NAME = table.Column<string>(type: "text", nullable: true),
                    FUNCTION = table.Column<string>(type: "text", nullable: true),
                    ELEMENT = table.Column<string>(type: "text", nullable: true),
                    PREDICAT = table.Column<string>(type: "text", nullable: true),
                    B = table.Column<string>(type: "text", nullable: true),
                    T = table.Column<string>(type: "text", nullable: true),
                    V = table.Column<string>(type: "text", nullable: true),
                    A1_B_F = table.Column<string>(type: "text", nullable: true),
                    B_F1N = table.Column<string>(type: "text", nullable: true),
                    B_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_B_F = table.Column<string>(type: "text", nullable: true),
                    B_F2N = table.Column<string>(type: "text", nullable: true),
                    B_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_B_F = table.Column<string>(type: "text", nullable: true),
                    B_F3N = table.Column<string>(type: "text", nullable: true),
                    B_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_T_F = table.Column<string>(type: "text", nullable: true),
                    T_F1N = table.Column<string>(type: "text", nullable: true),
                    T_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_T_F = table.Column<string>(type: "text", nullable: true),
                    T_F2N = table.Column<string>(type: "text", nullable: true),
                    T_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_T_F = table.Column<string>(type: "text", nullable: true),
                    T_F3N = table.Column<string>(type: "text", nullable: true),
                    T_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_V_F = table.Column<string>(type: "text", nullable: true),
                    V_F1N = table.Column<string>(type: "text", nullable: true),
                    V_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_V_F = table.Column<string>(type: "text", nullable: true),
                    V_F2N = table.Column<string>(type: "text", nullable: true),
                    V_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_V_F = table.Column<string>(type: "text", nullable: true),
                    V_F3N = table.Column<string>(type: "text", nullable: true),
                    V_F3B = table.Column<string>(type: "text", nullable: true),
                    K_11 = table.Column<string>(type: "text", nullable: true),
                    K_00 = table.Column<string>(type: "text", nullable: true),
                    T_F = table.Column<string>(type: "text", nullable: true),
                    V_F = table.Column<string>(type: "text", nullable: true),
                    A1_K11_F = table.Column<string>(type: "text", nullable: true),
                    K11_F1N = table.Column<string>(type: "text", nullable: true),
                    K11_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_K11_F = table.Column<string>(type: "text", nullable: true),
                    K11_F2N = table.Column<string>(type: "text", nullable: true),
                    K11_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_K11_F = table.Column<string>(type: "text", nullable: true),
                    K11_F3N = table.Column<string>(type: "text", nullable: true),
                    K11_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_K00_F = table.Column<string>(type: "text", nullable: true),
                    K00_F1N = table.Column<string>(type: "text", nullable: true),
                    K00_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_K00_F = table.Column<string>(type: "text", nullable: true),
                    K00_F2N = table.Column<string>(type: "text", nullable: true),
                    K00_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_K00_F = table.Column<string>(type: "text", nullable: true),
                    K00_F3N = table.Column<string>(type: "text", nullable: true),
                    K00_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_TF_F = table.Column<string>(type: "text", nullable: true),
                    TF_F1N = table.Column<string>(type: "text", nullable: true),
                    TF_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_TF_F = table.Column<string>(type: "text", nullable: true),
                    TF_F2N = table.Column<string>(type: "text", nullable: true),
                    TF_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_TF_F = table.Column<string>(type: "text", nullable: true),
                    TF_F3N = table.Column<string>(type: "text", nullable: true),
                    TF_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_VF_F = table.Column<string>(type: "text", nullable: true),
                    VF_F1N = table.Column<string>(type: "text", nullable: true),
                    VF_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_VF_F = table.Column<string>(type: "text", nullable: true),
                    VF_F2N = table.Column<string>(type: "text", nullable: true),
                    VF_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_VF_F = table.Column<string>(type: "text", nullable: true),
                    VF_F3N = table.Column<string>(type: "text", nullable: true),
                    VF_F3B = table.Column<string>(type: "text", nullable: true),
                    P_11 = table.Column<string>(type: "text", nullable: true),
                    P_00 = table.Column<string>(type: "text", nullable: true),
                    T_D = table.Column<string>(type: "text", nullable: true),
                    V_D = table.Column<string>(type: "text", nullable: true),
                    A1_P11_F = table.Column<string>(type: "text", nullable: true),
                    P11_F1N = table.Column<string>(type: "text", nullable: true),
                    P11_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_P11_F = table.Column<string>(type: "text", nullable: true),
                    P11_F2N = table.Column<string>(type: "text", nullable: true),
                    P11_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_P11_F = table.Column<string>(type: "text", nullable: true),
                    P11_F3N = table.Column<string>(type: "text", nullable: true),
                    P11_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_P00_F = table.Column<string>(type: "text", nullable: true),
                    P00_F1N = table.Column<string>(type: "text", nullable: true),
                    P00_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_P00_F = table.Column<string>(type: "text", nullable: true),
                    P00_F2N = table.Column<string>(type: "text", nullable: true),
                    P00_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_P00_F = table.Column<string>(type: "text", nullable: true),
                    P00_F3N = table.Column<string>(type: "text", nullable: true),
                    P00_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_TD_F = table.Column<string>(type: "text", nullable: true),
                    TD_F1N = table.Column<string>(type: "text", nullable: true),
                    TD_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_TD_F = table.Column<string>(type: "text", nullable: true),
                    TD_F2N = table.Column<string>(type: "text", nullable: true),
                    TD_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_TD_F = table.Column<string>(type: "text", nullable: true),
                    TD_F3N = table.Column<string>(type: "text", nullable: true),
                    TD_F3B = table.Column<string>(type: "text", nullable: true),
                    A1_VD_F = table.Column<string>(type: "text", nullable: true),
                    VD_F1N = table.Column<string>(type: "text", nullable: true),
                    VD_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_VD_F = table.Column<string>(type: "text", nullable: true),
                    VD_F2N = table.Column<string>(type: "text", nullable: true),
                    VD_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_VD_F = table.Column<string>(type: "text", nullable: true),
                    VD_F3N = table.Column<string>(type: "text", nullable: true),
                    VD_F3B = table.Column<string>(type: "text", nullable: true),
                    TYPE = table.Column<string>(type: "text", nullable: true),
                    ELEM_DIAGN = table.Column<string>(type: "text", nullable: true),
                    P_DIAGN_EL = table.Column<string>(type: "text", nullable: true),
                    A1_P_EL_F = table.Column<string>(type: "text", nullable: true),
                    P_EL_F1N = table.Column<string>(type: "text", nullable: true),
                    P_EL_F1B = table.Column<string>(type: "text", nullable: true),
                    A2_P_EL_F = table.Column<string>(type: "text", nullable: true),
                    P_EL_F2N = table.Column<string>(type: "text", nullable: true),
                    P_EL_F2B = table.Column<string>(type: "text", nullable: true),
                    A3_P_EL_F = table.Column<string>(type: "text", nullable: true),
                    P_EL_F3N = table.Column<string>(type: "text", nullable: true),
                    P_EL_F3B = table.Column<string>(type: "text", nullable: true),
                    SOVM = table.Column<string>(type: "text", nullable: true),
                    SOVM0 = table.Column<string>(type: "text", nullable: true),
                    SOVM1 = table.Column<string>(type: "text", nullable: true),
                    ROOTMAINLISTTFSTFEID = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ROOTMAINLISTTFSTFEPARAMSParamAlt", x => x.ID);
                    table.ForeignKey(
                        name: "FK_ROOTMAINLISTTFSTFEPARAMSParamAlt_ROOTMAINLISTTFSTFE_ROOTMAI~",
                        column: x => x.ROOTMAINLISTTFSTFEID,
                        principalTable: "ROOTMAINLISTTFSTFE",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ROOTMAINLISTTFSTFEPARAMSParamAlt_ROOTMAINLISTTFSTFEID",
                table: "ROOTMAINLISTTFSTFEPARAMSParamAlt",
                column: "ROOTMAINLISTTFSTFEID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ROOTMAINLISTTFSTFEPARAMSParamAlt");
        }
    }
}
