namespace TFS_Parser.Entities
{
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using Microsoft.EntityFrameworkCore;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 


    /// <remarks/>
 
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ROOT
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TFS", typeof(ROOTMAINLISTTFS),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTMAINLISTTFS> MAINLIST { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANCESTORLIST{ get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ALT", typeof(ROOTALTERNATELISTALT),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTALTERNATELISTALT> ALTERNATELIST{ get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OGRSOVMLIST{ get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TYPEPARAM", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTTYPEPARAM> TYPEPARAM { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TYPEDECISION",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTTYPEDECISION> TYPEDECISION { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ROOTMAINLISTTFS
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TFE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTMAINLISTTFSTFE> TFE { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Key]
        public string ID  {get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeID { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartPointX { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartPointY { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OffsetX { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OffsetY { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NextID { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PriorID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ROOTMAINLISTTFSTFE
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ParamAlt", typeof(ROOTMAINLISTTFSTFEPARAMSParamAlt),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ROOTMAINLISTTFSTFEPARAMSParamAlt> PARAMS { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Key]
        public string ID { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [Keyless]
    [NotMapped]
    public partial class ROOTMAINLISTTFSTFEPARAMSParamAlt
    {
        #region fields
        
        private string nUMBERField;

        private string pRED_ISTORField;

        private string sOSTAVField;

        private string nAMEField;

        private string fUNCTIONField;

        private string eLEMENTField;

        private string pREDICATField;

        private string bField;

        private string tField;

        private string vField;

        private string a1_B_FField;

        private string b_F1NField;

        private string b_F1BField;

        private string a2_B_FField;

        private string b_F2NField;

        private string b_F2BField;

        private string a3_B_FField;

        private string b_F3NField;

        private string b_F3BField;

        private string a1_T_FField;

        private string t_F1NField;

        private string t_F1BField;

        private string a2_T_FField;

        private string t_F2NField;

        private string t_F2BField;

        private string a3_T_FField;

        private string t_F3NField;

        private string t_F3BField;

        private string a1_V_FField;

        private string v_F1NField;

        private string v_F1BField;

        private string a2_V_FField;

        private string v_F2NField;

        private string v_F2BField;

        private string a3_V_FField;

        private string v_F3NField;

        private string v_F3BField;

        private string k_11Field;

        private string k_00Field;

        private string t_FField;

        private string v_FField;

        private string a1_K11_FField;

        private string k11_F1NField;

        private string k11_F1BField;

        private string a2_K11_FField;

        private string k11_F2NField;

        private string k11_F2BField;

        private string a3_K11_FField;

        private string k11_F3NField;

        private string k11_F3BField;

        private string a1_K00_FField;

        private string k00_F1NField;

        private string k00_F1BField;

        private string a2_K00_FField;

        private string k00_F2NField;

        private string k00_F2BField;

        private string a3_K00_FField;

        private string k00_F3NField;

        private string k00_F3BField;

        private string a1_TF_FField;

        private string tF_F1NField;

        private string tF_F1BField;

        private string a2_TF_FField;

        private string tF_F2NField;

        private string tF_F2BField;

        private string a3_TF_FField;

        private string tF_F3NField;

        private string tF_F3BField;

        private string a1_VF_FField;

        private string vF_F1NField;

        private string vF_F1BField;

        private string a2_VF_FField;

        private string vF_F2NField;

        private string vF_F2BField;

        private string a3_VF_FField;

        private string vF_F3NField;

        private string vF_F3BField;

        private string p_11Field;

        private string p_00Field;

        private string t_DField;

        private string v_DField;

        private string a1_P11_FField;

        private string p11_F1NField;

        private string p11_F1BField;

        private string a2_P11_FField;

        private string p11_F2NField;

        private string p11_F2BField;

        private string a3_P11_FField;

        private string p11_F3NField;

        private string p11_F3BField;

        private string a1_P00_FField;

        private string p00_F1NField;

        private string p00_F1BField;

        private string a2_P00_FField;

        private string p00_F2NField;

        private string p00_F2BField;

        private string a3_P00_FField;

        private string p00_F3NField;

        private string p00_F3BField;

        private string a1_TD_FField;

        private string tD_F1NField;

        private string tD_F1BField;

        private string a2_TD_FField;

        private string tD_F2NField;

        private string tD_F2BField;

        private string a3_TD_FField;

        private string tD_F3NField;

        private string tD_F3BField;

        private string a1_VD_FField;

        private string vD_F1NField;

        private string vD_F1BField;

        private string a2_VD_FField;

        private string vD_F2NField;

        private string vD_F2BField;

        private string a3_VD_FField;

        private string vD_F3NField;

        private string vD_F3BField;

        private string tYPEField;

        private string eLEM_DIAGNField;

        private string p_DIAGN_ELField;

        private string a1_P_EL_FField;

        private string p_EL_F1NField;

        private string p_EL_F1BField;

        private string a2_P_EL_FField;

        private string p_EL_F2NField;

        private string p_EL_F2BField;

        private string a3_P_EL_FField;

        private string p_EL_F3NField;

        private string p_EL_F3BField;

        private string sOVMField;

        private string sOVM0Field;

        private string sOVM1Field;
        
        #endregion

        #region properties

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NUMBER
        {
            get { return this.nUMBERField; }
            set { this.nUMBERField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PRED_ISTOR
        {
            get { return this.pRED_ISTORField; }
            set { this.pRED_ISTORField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SOSTAV
        {
            get { return this.sOSTAVField; }
            set { this.sOSTAVField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME
        {
            get { return this.nAMEField; }
            set { this.nAMEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FUNCTION
        {
            get { return this.fUNCTIONField; }
            set { this.fUNCTIONField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ELEMENT
        {
            get { return this.eLEMENTField; }
            set { this.eLEMENTField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PREDICAT
        {
            get { return this.pREDICATField; }
            set { this.pREDICATField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get { return this.bField; }
            set { this.bField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T
        {
            get { return this.tField; }
            set { this.tField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V
        {
            get { return this.vField; }
            set { this.vField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_B_F
        {
            get { return this.a1_B_FField; }
            set { this.a1_B_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B_F1N
        {
            get { return this.b_F1NField; }
            set { this.b_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B_F1B
        {
            get { return this.b_F1BField; }
            set { this.b_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_B_F
        {
            get { return this.a2_B_FField; }
            set { this.a2_B_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B_F2N
        {
            get { return this.b_F2NField; }
            set { this.b_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B_F2B
        {
            get { return this.b_F2BField; }
            set { this.b_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_B_F
        {
            get { return this.a3_B_FField; }
            set { this.a3_B_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B_F3N
        {
            get { return this.b_F3NField; }
            set { this.b_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B_F3B
        {
            get { return this.b_F3BField; }
            set { this.b_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_T_F
        {
            get { return this.a1_T_FField; }
            set { this.a1_T_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_F1N
        {
            get { return this.t_F1NField; }
            set { this.t_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_F1B
        {
            get { return this.t_F1BField; }
            set { this.t_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_T_F
        {
            get { return this.a2_T_FField; }
            set { this.a2_T_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_F2N
        {
            get { return this.t_F2NField; }
            set { this.t_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_F2B
        {
            get { return this.t_F2BField; }
            set { this.t_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_T_F
        {
            get { return this.a3_T_FField; }
            set { this.a3_T_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_F3N
        {
            get { return this.t_F3NField; }
            set { this.t_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_F3B
        {
            get { return this.t_F3BField; }
            set { this.t_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_V_F
        {
            get { return this.a1_V_FField; }
            set { this.a1_V_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_F1N
        {
            get { return this.v_F1NField; }
            set { this.v_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_F1B
        {
            get { return this.v_F1BField; }
            set { this.v_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_V_F
        {
            get { return this.a2_V_FField; }
            set { this.a2_V_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_F2N
        {
            get { return this.v_F2NField; }
            set { this.v_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_F2B
        {
            get { return this.v_F2BField; }
            set { this.v_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_V_F
        {
            get { return this.a3_V_FField; }
            set { this.a3_V_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_F3N
        {
            get { return this.v_F3NField; }
            set { this.v_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_F3B
        {
            get { return this.v_F3BField; }
            set { this.v_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K_11
        {
            get { return this.k_11Field; }
            set { this.k_11Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K_00
        {
            get { return this.k_00Field; }
            set { this.k_00Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_F
        {
            get { return this.t_FField; }
            set { this.t_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_F
        {
            get { return this.v_FField; }
            set { this.v_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_K11_F
        {
            get { return this.a1_K11_FField; }
            set { this.a1_K11_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K11_F1N
        {
            get { return this.k11_F1NField; }
            set { this.k11_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K11_F1B
        {
            get { return this.k11_F1BField; }
            set { this.k11_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_K11_F
        {
            get { return this.a2_K11_FField; }
            set { this.a2_K11_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K11_F2N
        {
            get { return this.k11_F2NField; }
            set { this.k11_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K11_F2B
        {
            get { return this.k11_F2BField; }
            set { this.k11_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_K11_F
        {
            get { return this.a3_K11_FField; }
            set { this.a3_K11_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K11_F3N
        {
            get { return this.k11_F3NField; }
            set { this.k11_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K11_F3B
        {
            get { return this.k11_F3BField; }
            set { this.k11_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_K00_F
        {
            get { return this.a1_K00_FField; }
            set { this.a1_K00_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K00_F1N
        {
            get { return this.k00_F1NField; }
            set { this.k00_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K00_F1B
        {
            get { return this.k00_F1BField; }
            set { this.k00_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_K00_F
        {
            get { return this.a2_K00_FField; }
            set { this.a2_K00_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K00_F2N
        {
            get { return this.k00_F2NField; }
            set { this.k00_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K00_F2B
        {
            get { return this.k00_F2BField; }
            set { this.k00_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_K00_F
        {
            get { return this.a3_K00_FField; }
            set { this.a3_K00_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K00_F3N
        {
            get { return this.k00_F3NField; }
            set { this.k00_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K00_F3B
        {
            get { return this.k00_F3BField; }
            set { this.k00_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_TF_F
        {
            get { return this.a1_TF_FField; }
            set { this.a1_TF_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TF_F1N
        {
            get { return this.tF_F1NField; }
            set { this.tF_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TF_F1B
        {
            get { return this.tF_F1BField; }
            set { this.tF_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_TF_F
        {
            get { return this.a2_TF_FField; }
            set { this.a2_TF_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TF_F2N
        {
            get { return this.tF_F2NField; }
            set { this.tF_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TF_F2B
        {
            get { return this.tF_F2BField; }
            set { this.tF_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_TF_F
        {
            get { return this.a3_TF_FField; }
            set { this.a3_TF_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TF_F3N
        {
            get { return this.tF_F3NField; }
            set { this.tF_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TF_F3B
        {
            get { return this.tF_F3BField; }
            set { this.tF_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_VF_F
        {
            get { return this.a1_VF_FField; }
            set { this.a1_VF_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VF_F1N
        {
            get { return this.vF_F1NField; }
            set { this.vF_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VF_F1B
        {
            get { return this.vF_F1BField; }
            set { this.vF_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_VF_F
        {
            get { return this.a2_VF_FField; }
            set { this.a2_VF_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VF_F2N
        {
            get { return this.vF_F2NField; }
            set { this.vF_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VF_F2B
        {
            get { return this.vF_F2BField; }
            set { this.vF_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_VF_F
        {
            get { return this.a3_VF_FField; }
            set { this.a3_VF_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VF_F3N
        {
            get { return this.vF_F3NField; }
            set { this.vF_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VF_F3B
        {
            get { return this.vF_F3BField; }
            set { this.vF_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_11
        {
            get { return this.p_11Field; }
            set { this.p_11Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_00
        {
            get { return this.p_00Field; }
            set { this.p_00Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T_D
        {
            get { return this.t_DField; }
            set { this.t_DField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V_D
        {
            get { return this.v_DField; }
            set { this.v_DField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_P11_F
        {
            get { return this.a1_P11_FField; }
            set { this.a1_P11_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P11_F1N
        {
            get { return this.p11_F1NField; }
            set { this.p11_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P11_F1B
        {
            get { return this.p11_F1BField; }
            set { this.p11_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_P11_F
        {
            get { return this.a2_P11_FField; }
            set { this.a2_P11_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P11_F2N
        {
            get { return this.p11_F2NField; }
            set { this.p11_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P11_F2B
        {
            get { return this.p11_F2BField; }
            set { this.p11_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_P11_F
        {
            get { return this.a3_P11_FField; }
            set { this.a3_P11_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P11_F3N
        {
            get { return this.p11_F3NField; }
            set { this.p11_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P11_F3B
        {
            get { return this.p11_F3BField; }
            set { this.p11_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_P00_F
        {
            get { return this.a1_P00_FField; }
            set { this.a1_P00_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P00_F1N
        {
            get { return this.p00_F1NField; }
            set { this.p00_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P00_F1B
        {
            get { return this.p00_F1BField; }
            set { this.p00_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_P00_F
        {
            get { return this.a2_P00_FField; }
            set { this.a2_P00_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P00_F2N
        {
            get { return this.p00_F2NField; }
            set { this.p00_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P00_F2B
        {
            get { return this.p00_F2BField; }
            set { this.p00_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_P00_F
        {
            get { return this.a3_P00_FField; }
            set { this.a3_P00_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P00_F3N
        {
            get { return this.p00_F3NField; }
            set { this.p00_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P00_F3B
        {
            get { return this.p00_F3BField; }
            set { this.p00_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_TD_F
        {
            get { return this.a1_TD_FField; }
            set { this.a1_TD_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TD_F1N
        {
            get { return this.tD_F1NField; }
            set { this.tD_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TD_F1B
        {
            get { return this.tD_F1BField; }
            set { this.tD_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_TD_F
        {
            get { return this.a2_TD_FField; }
            set { this.a2_TD_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TD_F2N
        {
            get { return this.tD_F2NField; }
            set { this.tD_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TD_F2B
        {
            get { return this.tD_F2BField; }
            set { this.tD_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_TD_F
        {
            get { return this.a3_TD_FField; }
            set { this.a3_TD_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TD_F3N
        {
            get { return this.tD_F3NField; }
            set { this.tD_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TD_F3B
        {
            get { return this.tD_F3BField; }
            set { this.tD_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_VD_F
        {
            get { return this.a1_VD_FField; }
            set { this.a1_VD_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VD_F1N
        {
            get { return this.vD_F1NField; }
            set { this.vD_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VD_F1B
        {
            get { return this.vD_F1BField; }
            set { this.vD_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_VD_F
        {
            get { return this.a2_VD_FField; }
            set { this.a2_VD_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VD_F2N
        {
            get { return this.vD_F2NField; }
            set { this.vD_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VD_F2B
        {
            get { return this.vD_F2BField; }
            set { this.vD_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_VD_F
        {
            get { return this.a3_VD_FField; }
            set { this.a3_VD_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VD_F3N
        {
            get { return this.vD_F3NField; }
            set { this.vD_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VD_F3B
        {
            get { return this.vD_F3BField; }
            set { this.vD_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE
        {
            get { return this.tYPEField; }
            set { this.tYPEField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ELEM_DIAGN
        {
            get { return this.eLEM_DIAGNField; }
            set { this.eLEM_DIAGNField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_DIAGN_EL
        {
            get { return this.p_DIAGN_ELField; }
            set { this.p_DIAGN_ELField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A1_P_EL_F
        {
            get { return this.a1_P_EL_FField; }
            set { this.a1_P_EL_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_EL_F1N
        {
            get { return this.p_EL_F1NField; }
            set { this.p_EL_F1NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_EL_F1B
        {
            get { return this.p_EL_F1BField; }
            set { this.p_EL_F1BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A2_P_EL_F
        {
            get { return this.a2_P_EL_FField; }
            set { this.a2_P_EL_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_EL_F2N
        {
            get { return this.p_EL_F2NField; }
            set { this.p_EL_F2NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_EL_F2B
        {
            get { return this.p_EL_F2BField; }
            set { this.p_EL_F2BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A3_P_EL_F
        {
            get { return this.a3_P_EL_FField; }
            set { this.a3_P_EL_FField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_EL_F3N
        {
            get { return this.p_EL_F3NField; }
            set { this.p_EL_F3NField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P_EL_F3B
        {
            get { return this.p_EL_F3BField; }
            set { this.p_EL_F3BField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SOVM
        {
            get { return this.sOVMField; }
            set { this.sOVMField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SOVM0
        {
            get { return this.sOVM0Field; }
            set { this.sOVM0Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SOVM1
        {
            get { return this.sOVM1Field; }
            set { this.sOVM1Field = value; }
        }
        
        #endregion
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ROOTALTERNATELISTALT
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTALTERNATELISTALTITEM> ITEM { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Key]
        public string ID { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Num { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeStartID { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeEndID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ROOTALTERNATELISTALTITEM
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ROOTTYPEPARAM
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Key]
        public string ID { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value { get; set; }
        
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ROOTTYPEDECISION
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Key]
        public string ID { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Params", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ROOTTYPEDECISIONParams> Params { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sovm { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ROOTTYPEDECISIONParams
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Key]
        public string ID { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VD{ get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TD{ get; set; }
    }

}